//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarbageCollectionPolicy) DeepCopyInto(out *GarbageCollectionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarbageCollectionPolicy.
func (in *GarbageCollectionPolicy) DeepCopy() *GarbageCollectionPolicy {
	if in == nil {
		return nil
	}
	out := new(GarbageCollectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GarbageCollectionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarbageCollectionPolicyList) DeepCopyInto(out *GarbageCollectionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GarbageCollectionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarbageCollectionPolicyList.
func (in *GarbageCollectionPolicyList) DeepCopy() *GarbageCollectionPolicyList {
	if in == nil {
		return nil
	}
	out := new(GarbageCollectionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GarbageCollectionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarbageCollectionPolicySpec) DeepCopyInto(out *GarbageCollectionPolicySpec) {
	*out = *in
	in.TargetResource.DeepCopyInto(&out.TargetResource)
	in.TTL.DeepCopyInto(&out.TTL)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new(ConditionsSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Behavior.DeepCopyInto(&out.Behavior)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarbageCollectionPolicySpec.
func (in *GarbageCollectionPolicySpec) DeepCopy() *GarbageCollectionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GarbageCollectionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GarbageCollectionPolicyStatus) DeepCopyInto(out *GarbageCollectionPolicyStatus) {
	*out = *in
	if in.LastGCRun != nil {
		in, out := &in.LastGCRun, &out.LastGCRun
		*out = (*in).DeepCopy()
	}
	if in.NextGCRun != nil {
		in, out := &in.NextGCRun, &out.NextGCRun
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GarbageCollectionPolicyStatus.
func (in *GarbageCollectionPolicyStatus) DeepCopy() *GarbageCollectionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GarbageCollectionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetResourceSpec) DeepCopyInto(out *TargetResourceSpec) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FieldSelector != nil {
		in, out := &in.FieldSelector, &out.FieldSelector
		*out = new(FieldSelectorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetResourceSpec.
func (in *TargetResourceSpec) DeepCopy() *TargetResourceSpec {
	if in == nil {
		return nil
	}
	out := new(TargetResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TTLSpec) DeepCopyInto(out *TTLSpec) {
	*out = *in
	if in.SecondsAfterCreation != nil {
		in, out := &in.SecondsAfterCreation, &out.SecondsAfterCreation
		*out = new(int64)
		**out = **in
	}
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(int64)
		**out = **in
	}
	if in.SecondsAfter != nil {
		in, out := &in.SecondsAfter, &out.SecondsAfter
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TTLSpec.
func (in *TTLSpec) DeepCopy() *TTLSpec {
	if in == nil {
		return nil
	}
	out := new(TTLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsSpec) DeepCopyInto(out *ConditionsSpec) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HasLabels != nil {
		in, out := &in.HasLabels, &out.HasLabels
		*out = make([]LabelCondition, len(*in))
		copy(*out, *in)
	}
	if in.HasAnnotations != nil {
		in, out := &in.HasAnnotations, &out.HasAnnotations
		*out = make([]AnnotationCondition, len(*in))
		copy(*out, *in)
	}
	if in.And != nil {
		in, out := &in.And, &out.And
		*out = make([]FieldCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsSpec.
func (in *ConditionsSpec) DeepCopy() *ConditionsSpec {
	if in == nil {
		return nil
	}
	out := new(ConditionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BehaviorSpec) DeepCopyInto(out *BehaviorSpec) {
	*out = *in
	if in.GracePeriodSeconds != nil {
		in, out := &in.GracePeriodSeconds, &out.GracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BehaviorSpec.
func (in *BehaviorSpec) DeepCopy() *BehaviorSpec {
	if in == nil {
		return nil
	}
	out := new(BehaviorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldSelectorSpec) DeepCopyInto(out *FieldSelectorSpec) {
	*out = *in
	if in.MatchFields != nil {
		in, out := &in.MatchFields, &out.MatchFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldSelectorSpec.
func (in *FieldSelectorSpec) DeepCopy() *FieldSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(FieldSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelCondition) DeepCopyInto(out *LabelCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelCondition.
func (in *LabelCondition) DeepCopy() *LabelCondition {
	if in == nil {
		return nil
	}
	out := new(LabelCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotationCondition) DeepCopyInto(out *AnnotationCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationCondition.
func (in *AnnotationCondition) DeepCopy() *AnnotationCondition {
	if in == nil {
		return nil
	}
	out := new(AnnotationCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldCondition) DeepCopyInto(out *FieldCondition) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldCondition.
func (in *FieldCondition) DeepCopy() *FieldCondition {
	if in == nil {
		return nil
	}
	out := new(FieldCondition)
	in.DeepCopyInto(out)
	return out
}

